note when Wrath die is 6
When die is 6, report "++" as in:

Successes: 5   Sixes: 1   Wrath: 6 ++   D6: 4 4 2 2 5

Change `VERSION` to "1.1.0 2026-05-29`.

diff --git a/wd6 b/wd6
--- a/wd6
+++ b/wd6
@@ -2,9 +2,9 @@
 #
 # wd6 - Warhammer 40k dice system
 #
-# Roll 2 or more D6 dice, where the 1st die is the Wrath die.
+# Roll 1 or more D6 dice, where the 1st die is the Wrath die.
 #
-# Count successes, sixes, and note if the Wrath die is 1.
+# Count successes, sixes, and note if the Wrath die is 1 or 6.
 #
 # Copyright (c) 2026 by Landon Curt Noll.  All Rights Reserved.
 #
@@ -36,7 +36,7 @@
 
 # setup
 #
-export VERSION="1.0.0 2026-05-29"
+export VERSION="1.1.0 2026-05-29"
 NAME=$(basename "$0")
 export NAME
 #
@@ -139,8 +139,8 @@ if ! [[ $COUNT =~ $re ]] ; then
    echo "$0: ERROR: count arg must be a number: $COUNT" 1>&2
    exit 1
 fi
-if [[ $COUNT -lt 2 ]]; then
-   echo "$0: ERROR: count arg must >= 2: $COUNT" 1>&2
+if [[ $COUNT -lt 1 ]]; then
+   echo "$0: ERROR: count arg must >= 1: $COUNT" 1>&2
    exit 1
 fi
 ((D6_COUNT=COUNT-1))
@@ -206,18 +206,22 @@ if [[ -z $NOOP ]]; then
 
     # roll the other D6 dice
     #
-    if [[ $V_FLAG -ge 1 ]]; then
-        echo "$0: debug[1]: about to run: $SHUF_TOOL -i 1-6 -n $D6_COUNT --repeat" 1>&2
-    fi
-    mapfile -t D6_SET < <("$SHUF_TOOL" -i 1-6 -n "$D6_COUNT" --repeat)
-    status="$?"
-    if [[ $status -ne 0 || ${#D6_SET[@]} -le 0 ]]; then
-	echo "$0: ERROR:" \
-	    "mapfile -t D6_SET < <($SHUF_TOOL -i 1-6 -n $D6_COUNT --repeat) failed, error: $status" 1>&2
-	exit 1
-    fi
-    if [[ $V_FLAG -ge 1 ]]; then
-	echo "$0: debug[1]: Warth: $WRATH D6: ${D6_SET[*]}"
+    if [[ $D6_COUNT -ge 1 ]]; then
+	if [[ $V_FLAG -ge 1 ]]; then
+	    echo "$0: debug[1]: about to run: $SHUF_TOOL -i 1-6 -n $D6_COUNT --repeat" 1>&2
+	fi
+	mapfile -t D6_SET < <("$SHUF_TOOL" -i 1-6 -n "$D6_COUNT" --repeat)
+	status="$?"
+	if [[ $status -ne 0 || ${#D6_SET[@]} -le 0 ]]; then
+	    echo "$0: ERROR:" \
+		"mapfile -t D6_SET < <($SHUF_TOOL -i 1-6 -n $D6_COUNT --repeat) failed, error: $status" 1>&2
+	    exit 1
+	fi
+	if [[ $V_FLAG -ge 1 ]]; then
+	    echo "$0: debug[1]: Warth: $WRATH D6: ${D6_SET[*]}"
+	fi
+    elif [[ $V_FLAG -ge 1 ]]; then
+	echo "$0: debug[1]: Warth: $WRATH"
     fi
 
     # count successes
@@ -235,24 +239,30 @@ if [[ -z $NOOP ]]; then
 	exit 1
 	;;
     esac
-    for d6 in "${D6_SET[@]}"; do
-	case "$d6" in
-	1) ;;
-	2) ;;
-	3) ;;
-	4) ((++SUCCESS)) ;;
-	5) ((++SUCCESS)) ;;
-	6) ((SUCCESS+=2)); ((++SIX_COUNT)) ;;
-	*)  echo "$0: ERROR: D6 value is invalid: $d6" 1>&2
-	    exit 1
-	    ;;
-	esac
-    done
+    if [[ $D6_COUNT -ge 1 ]]; then
+	for d6 in "${D6_SET[@]}"; do
+	    case "$d6" in
+	    1) ;;
+	    2) ;;
+	    3) ;;
+	    4) ((++SUCCESS)) ;;
+	    5) ((++SUCCESS)) ;;
+	    6) ((SUCCESS+=2)); ((++SIX_COUNT)) ;;
+	    *)  echo "$0: ERROR: D6 value is invalid: $d6" 1>&2
+		exit 1
+		;;
+	    esac
+	done
+    else
+	D6_SET=()
+    fi
 
     # report
     #
     if [[ $WRATH -eq 1 ]]; then
 	echo "Successes: $SUCCESS   Sixes: $SIX_COUNT   Wrath: $WRATH !!   D6: ${D6_SET[*]}"
+    elif [[ $WRATH -eq 6 ]]; then
+	echo "Successes: $SUCCESS   Sixes: $SIX_COUNT   Wrath: $WRATH ++   D6: ${D6_SET[*]}"
     else
 	echo "Successes: $SUCCESS   Sixes: $SIX_COUNT   Wrath: $WRATH ..   D6: ${D6_SET[*]}"
     fi
